### ISSUE TITLE
您好，小白想请教一下这个BI公式的具体意义是什么呢？

### ISSUE THREAD

**Issue by Tompes** [algosenses/Stock_Market_Sentiment_Analysis#5]
您好，小白想请教一下这个BI公式的具体意义是什么呢？

**Comment by TerenceLiu98** [comment]
This BI formula is produced by WERNER ANTWEILER and MURRAY Z. FRANK in their paper:[ _**Is All That Talk Just Noise? The Information Content of Internet Stock Message Boards**_ . ](https://doi.org/10.1111/j.1540-6261.2004.00662.x)

**Comment by Tompes** [comment]
> This BI formula is produced by WERNER ANTWEILER and MURRAY Z. FRANK in their paper:[ _**Is All That Talk Just Noise? The Information Content of Internet Stock Message Boards**_ . ](https://doi.org/10.1111/j.1540-6261.2004.00662.x)

谢谢！
